# Generated by Django 4.1.2 on 2022-10-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="university",
            name="full_name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="university",
            name="short_name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
